# Default values for api-subscription.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

affinity: {}

args: []

config: {}

env: []
  # - name: MY_STATIC_VAR
  #   value: "my_value"
  # - name: MY_CONFIG_VAR
  #   valueFrom:
  #     configMapKeyRef:
  #       name: my-configmap
  #       key: config-key
  #       optional: false
  # - name: MY_SECRET_VAR
  #   valueFrom:
  #     secretKeyRef:
  #       name: my-secret
  #       key: secret-key
  #       optional: false

envFrom: []
  # - configMapRef:
  #     name: my-configmap
  #     optional: false
  # - secretRef:
  #     name: my-secret
  #     optional: false

secrets: []
  # - name: cert-secret
  #   secretName: my-certificate-secret
  #   mountPath: /etc/certs
  #   readOnly: true
  #   optional: false

configMaps: []
  # - name: app-config
  #   configMapName: my-app-config
  #   mountPath: /etc/config
  #   readOnly: true
  #   optional: false

volume:
  data:
    volumeClaim: ""