stages:
  - generate

chart-generator:
  stage: generate
  image: alpine:3.15
  script:
    - ./scripts/generate-pipeline.sh > generated-pipeline.yml
  artifacts:
    expire_in: 1 hour
    paths:
      - generated-pipeline.yml
#  rules:
#    - if: '$CI_COMMIT_TAG =~ "/^$/"'
#      changes:
#        - charts/**/*

chart-jobs:
  stage: generate
  needs:
    - chart-generator
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: chart-generator
    strategy: depend
#  rules:
#    - if: '$CI_COMMIT_TAG =~ "/^$/"'
#      changes:
#        - charts/**/*