apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pim-cronjob.fullname" . }}
  labels:
    {{- include "pim-cronjob.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | quote }}
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "pim-cronjob.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ printf "%s" .Chart.Name | lower | trunc 63 | trimSuffix "-" }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.podEnv }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{ toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /python-docker/config
                  readOnly: true
          nodeSelector:
            {{ toYaml .Values.nodeSelector | nindent 12 }}
          affinity:
            {{ toYaml .Values.affinity | nindent 12 }}
          tolerations:
            {{ toYaml .Values.tolerations | nindent 12 }}
          imagePullSecrets:
            {{ toYaml .Values.imagePullSecrets | nindent 12 }}
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: {{ include "pim-cronjob.fullname" . }}