apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sensa.fullname" . }}
  labels:
{{ include "sensa.labels" . | indent 4 }}
data:
  config.json: {{ .Values.config | toJson | quote }}
