{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "api-manager-deployment.selectorLabels" . | nindent 4 }}
  name: {{ include "api-manager-deployment.fullname" . }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - list
      - delete
{{- end -}}
