apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-manager-deployment.fullname" . }}
  labels:
    {{- include "api-manager-deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-manager-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-manager-deployment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-manager-deployment.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- range .Values.globalArgs }}
            - {{ . | quote }}
          {{- end }}
          {{- range .Values.args }}
            - {{ . | quote }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.config }}
            - name: config
              mountPath: /etc/nx
              readOnly: true
          {{- end }}
          {{- range .Values.secrets }}
            - name: {{ .name | quote }}
              mountPath: {{ .mountPath | quote }}
              readOnly: {{ .readOnly | default true }}
          {{- end }}
          {{- range .Values.configMaps }}
            - name: {{ .name | quote }}
              mountPath: {{ .mountPath | quote }}
              readOnly: {{ .readOnly | default true }}
          {{- end }}
          {{- range .Values.csiSecrets }}
            - name: {{ .name | quote }}
              mountPath: {{ .mountPath | quote }}
              readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with .Values.config }}
        - name: config
          configMap:
            name: {{ include "api-manager-deployment.fullname" $ }}
        {{- end }}
        {{- range .Values.secrets }}
        - name: {{ .name | quote }}
          secret:
            secretName: {{ .secretName | quote }}
            optional: {{ .optional | default false }}
        {{- end }}
        {{- range .Values.configMaps }}
        - name: {{ .name | quote }}
          configMap:
            name: {{ .configMapName | quote }}
            optional: {{ .optional | default false }}
        {{- end }}
        {{- range .Values.csiSecrets }}
        - name: {{ .name | quote }}
          csi:
            driver: {{ .driver | default "secrets-store-gke.csi.k8s.io" }}
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .secretProviderClass | quote }}
        {{- end }}
