{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "negsoft-operator.labels" . | nindent 4 }}
  name: {{ include "negsoft-operator.fullname" . }}-update-cronjobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "negsoft-operator.fullname" . }}-update-cronjobs
subjects:
  - kind: ServiceAccount
    name: {{ include "negsoft-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "negsoft-operator.labels" . | nindent 4 }}
  name: {{ include "negsoft-operator.fullname" . }}-read-subscriptions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "negsoft-operator.fullname" . }}-read-subscriptions
subjects:
  - kind: ServiceAccount
    name: {{ include "negsoft-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
