apiVersion: v1
kind: Secret
metadata:
  name: {{ include "negsoft-operator.fullname" . }}-secret
  labels:
    {{- include "negsoft-operator.labels" . | nindent 4 }}
type: Opaque
data:
  mssqlHostname: {{ .Values.secret.mssqlHostname | b64enc | quote }}
  mssqlPort: {{ .Values.secret.mssqlPort | b64enc | quote }}
  mssqlUsername: {{ .Values.secret.mssqlUsername | b64enc | quote }}
  mssqlPassword: {{ .Values.secret.mssqlPassword | b64enc | quote }}
  redisAddresses: {{ .Values.secret.redisAddresses | b64enc | quote }}
  redisMasterSet: {{ .Values.secret.redisMasterSet | b64enc | quote }}
  redisDatabase: {{ .Values.secret.redisDatabase | b64enc | quote }}