{{- if or .Values.serial.rtf2html .Values.serial.html2rtf -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "rtf2html.labels" . | nindent 4 }}
  name: {{ include "rtf2html.fullname" . }}
data:
  {{- if .Values.serial.rtf2html }}
  serial-rtf2html: {{ .Values.serial.rtf2html | b64enc | quote }}
  {{- end }}
  {{- if .Values.serial.html2rtf }}
  serial-html2rtf: {{ .Values.serial.html2rtf | b64enc | quote }}
  {{- end }}
{{- end -}}

