{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "api-deployment.fullname" . }}
  labels:
    {{- include "api-deployment.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "api-deployment.fullname" . }}
  {{ toYaml .Values.autoscaling.config | nindent 2 }}
{{- end }}
